USE [ACT]
GO

--SELECT [PK]
--      ,[visible]
--      ,[dbid]
--      ,[ts]
--      ,[last_update]
--      ,[version]
--      ,[bio]
--      ,[displayname]
--      ,[crc]
--      ,[playedtime]
--      ,[id]
--      ,[ascension_list]
--      ,[ascension.active.name]
--      ,[ascension.elementalist.active]
--      ,[ascension.elementalist.xpfornextlevel]
--      ,[ascension.elementalist.name]
--      ,[ascension.elementalist.currentxp]
--      ,[ascension.elementalist.level]
--      ,[ascension.etherealist.active]
--      ,[ascension.etherealist.xpfornextlevel]
--      ,[ascension.etherealist.name]
--      ,[ascension.etherealist.currentxp]
--      ,[ascension.etherealist.level]
--      ,[ascension.geomancer.active]
--      ,[ascension.geomancer.xpfornextlevel]
--      ,[ascension.geomancer.name]
--      ,[ascension.geomancer.currentxp]
--      ,[ascension.geomancer.level]
--      ,[ascension.thaumaturgist.active]
--      ,[ascension.thaumaturgist.xpfornextlevel]
--      ,[ascension.thaumaturgist.name]
--      ,[ascension.thaumaturgist.currentxp]
--      ,[ascension.thaumaturgist.level]
--      ,[type.classid]
--      ,[type.aa_level]
--      ,[type.ts_level]
--      ,[type.raceid]
--      ,[type.level]
--      ,[type.gender]
--      ,[type.ts_class]
--      ,[type.birthdate_utc]
--      ,[type.race]
--      ,[type.deity]
--      ,[type.class]
--      ,[type.alignment]
--      ,[tradeskills.*.level]
--      ,[locationdata.worldid]
--      ,[locationdata.world]
--      ,[name.prefix]
--      ,[name.first_lower]
--      ,[name.last]
--      ,[name.suffix]
--      ,[name.first]
--      ,[account.age]
--      ,[account.link_id]
--      ,[guild.status]
--      ,[guild.name]
--      ,[guild.level]
--      ,[guild.joined]
--      ,[guild.rank]
--      ,[guild.guildid]
--      ,[guild.id]
--      ,[sort]
--      ,[RN]
--      ,[DBInsDate]
--      ,[DBUpdDate]
--      ,[TS1]
--      ,[GRID]
--  FROM [dbo].[character.thurgadin]
--GO


delete from a
from
(
select [visible]
      ,[dbid]
     -- ,[ts]
    --  ,[last_update]
      ,[version]
      ,[bio]
      ,[displayname]
      --,[crc]
     -- ,[playedtime]
      ,[id]
      ,[ascension_list]
      ,[ascension.active.name]
      ,[ascension.elementalist.active]
      ,[ascension.elementalist.xpfornextlevel]
      ,[ascension.elementalist.name]
      ,[ascension.elementalist.currentxp]
      ,[ascension.elementalist.level]
      ,[ascension.etherealist.active]
      ,[ascension.etherealist.xpfornextlevel]
      ,[ascension.etherealist.name]
      ,[ascension.etherealist.currentxp]
      ,[ascension.etherealist.level]
      ,[ascension.geomancer.active]
      ,[ascension.geomancer.xpfornextlevel]
      ,[ascension.geomancer.name]
      ,[ascension.geomancer.currentxp]
      ,[ascension.geomancer.level]
      ,[ascension.thaumaturgist.active]
      ,[ascension.thaumaturgist.xpfornextlevel]
      ,[ascension.thaumaturgist.name]
      ,[ascension.thaumaturgist.currentxp]
      ,[ascension.thaumaturgist.level]
      ,[type.classid]
      ,[type.aa_level]
      ,[type.ts_level]
      ,[type.raceid]
      ,[type.level]
      ,[type.gender]
      ,[type.ts_class]
      ,[type.birthdate_utc]
      ,[type.race]
      ,[type.deity]
      ,[type.class]
      ,[type.alignment]
      ,[tradeskills.*.level]
      ,[locationdata.worldid]
      ,[locationdata.world]
      ,[name.prefix]
      ,[name.first_lower]
      ,[name.last]
      ,[name.suffix]
      ,[name.first]
      ,[account.age]
      ,[account.link_id]
      ,[guild.status]
      ,[guild.name]
      ,[guild.level]
      ,[guild.joined]
      ,[guild.rank]
      ,[guild.guildid]
      ,[guild.id]
       ,ROW_NUMBER() over (partition by [visible]
      ,[dbid]
     -- ,[ts]
     -- ,[last_update]
      ,[version]
      ,[bio]
      ,[displayname]
      --,[crc]
     -- ,[playedtime]
      ,[id]
      ,[ascension_list]
      ,[ascension.active.name]
      ,[ascension.elementalist.active]
      ,[ascension.elementalist.xpfornextlevel]
      ,[ascension.elementalist.name]
      ,[ascension.elementalist.currentxp]
      ,[ascension.elementalist.level]
      ,[ascension.etherealist.active]
      ,[ascension.etherealist.xpfornextlevel]
      ,[ascension.etherealist.name]
      ,[ascension.etherealist.currentxp]
      ,[ascension.etherealist.level]
      ,[ascension.geomancer.active]
      ,[ascension.geomancer.xpfornextlevel]
      ,[ascension.geomancer.name]
      ,[ascension.geomancer.currentxp]
      ,[ascension.geomancer.level]
      ,[ascension.thaumaturgist.active]
      ,[ascension.thaumaturgist.xpfornextlevel]
      ,[ascension.thaumaturgist.name]
      ,[ascension.thaumaturgist.currentxp]
      ,[ascension.thaumaturgist.level]
      ,[type.classid]
      ,[type.aa_level]
      ,[type.ts_level]
      ,[type.raceid]
      ,[type.level]
      ,[type.gender]
      ,[type.ts_class]
      ,[type.birthdate_utc]
      ,[type.race]
      ,[type.deity]
      ,[type.class]
      ,[type.alignment]
      ,[tradeskills.*.level]
      ,[locationdata.worldid]
      ,[locationdata.world]
      ,[name.prefix]
      ,[name.first_lower]
      ,[name.last]
      ,[name.suffix]
      ,[name.first]
      ,[account.age]
      ,[account.link_id]
      ,[guild.status]
      ,[guild.name]
      ,[guild.level]
      ,[guild.joined]
      ,[guild.rank]
      ,[guild.guildid]
      ,[guild.id]
                           order by 
					  [visible]
      ,[dbid]
     -- ,[ts]
      --,[last_update]
      ,[version]
      ,[bio]
      ,[displayname]
      --,[crc]
     -- ,[playedtime]
      ,[id]
      ,[ascension_list]
      ,[ascension.active.name]
      ,[ascension.elementalist.active]
      ,[ascension.elementalist.xpfornextlevel]
      ,[ascension.elementalist.name]
      ,[ascension.elementalist.currentxp]
      ,[ascension.elementalist.level]
      ,[ascension.etherealist.active]
      ,[ascension.etherealist.xpfornextlevel]
      ,[ascension.etherealist.name]
      ,[ascension.etherealist.currentxp]
      ,[ascension.etherealist.level]
      ,[ascension.geomancer.active]
      ,[ascension.geomancer.xpfornextlevel]
      ,[ascension.geomancer.name]
      ,[ascension.geomancer.currentxp]
      ,[ascension.geomancer.level]
      ,[ascension.thaumaturgist.active]
      ,[ascension.thaumaturgist.xpfornextlevel]
      ,[ascension.thaumaturgist.name]
      ,[ascension.thaumaturgist.currentxp]
      ,[ascension.thaumaturgist.level]
      ,[type.classid]
      ,[type.aa_level]
      ,[type.ts_level]
      ,[type.raceid]
      ,[type.level]
      ,[type.gender]
      ,[type.ts_class]
      ,[type.birthdate_utc]
      ,[type.race]
      ,[type.deity]
      ,[type.class]
      ,[type.alignment]
      ,[tradeskills.*.level]
      ,[locationdata.worldid]
      ,[locationdata.world]
      ,[name.prefix]
      ,[name.first_lower]
      ,[name.last]
      ,[name.suffix]
      ,[name.first]
      ,[account.age]
      ,[account.link_id]
      ,[guild.status]
      ,[guild.name]
      ,[guild.level]
      ,[guild.joined]
      ,[guild.rank]
      ,[guild.guildid]
      ,[guild.id]
	 ) RowNumber 
from [dbo].[character.thurgadin]) a
where a.RowNumber > 1